# Generated by Django 4.0.6 on 2022-07-13 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('birthday', models.DateField()),
                ('favorite_flavor', models.CharField(choices=[('VAN', 'Very Vanilla'), ('CHO', 'Crazy Coco'), ('STB', 'Sweetie Strawberry'), ('BC', 'Birthday Bonanza'), ('LEM', 'Loco Lemon'), ('WCR', 'White Coco Razz'), ('GFCC', 'Gluten Free Cookie Craze'), ('RV', 'Ridiculous Red Velvet'), ('CIN', 'Scintillating Cinnamon'), ('CAR', 'Crisp Carrot')], default='Very Vanilla', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('total', models.IntegerField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes_app.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(choices=[('VAN', 'Very Vanilla'), ('CHO', 'Crazy Coco'), ('STB', 'Sweetie Strawberry'), ('BC', 'Birthday Bonanza'), ('LEM', 'Loco Lemon'), ('WCR', 'White Coco Razz'), ('GFCC', 'Gluten Free Cookie Craze'), ('RV', 'Ridiculous Red Velvet'), ('CIN', 'Scintillating Cinnamon'), ('CAR', 'Crisp Carrot')], max_length=5)),
                ('occasion', models.CharField(max_length=100)),
                ('frosting_level', models.CharField(choices=[('NO', 'None'), ('DRI', 'Drizzle'), ('NOR', 'Normal'), ('EXT', 'Extra')], default='Normal', max_length=5)),
                ('decoration', models.CharField(choices=[('BIR', 'Happy Birthday'), ('GRD', 'Graduation'), ('IND', 'Independence Day'), ('THK', 'Thank You'), ('JB', 'Just Because'), ('NO', 'None')], default='None', max_length=5)),
                ('message_card', models.CharField(blank=True, max_length=200)),
                ('size', models.CharField(choices=[('DOZ', 'Dozen Cupcakes'), ('PER', 'Personal Size Cake'), ('TOW', 'Triple Tower Personal Size Cakes'), ('BOX', '12 box of Personal Size Cakes'), ('8IN', '8 Inch Cake'), ('10IN', '10 Inch Cake'), ('LAY', 'Layered Cake(10in bottom 8in top)')], max_length=5)),
                ('qty', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes_app.cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakes_app.guest'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakes_app.guest')),
            ],
        ),
    ]
