# Generated by Django 4.0.6 on 2022-07-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guest',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
