# Generated by Django 4.0.6 on 2022-07-22 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='cakes_app.guest'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='cakes_app.guest'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cakes_app.cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='occasion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase_history',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='cakes_app.guest'),
        ),
    ]
