# Generated by Django 4.0.6 on 2022-07-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_app', '0002_alter_address_guest_alter_cart_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='favorite_flavor',
            field=models.CharField(choices=[('Very Vanilla', 'Very Vanilla'), ('Crazy Coco', 'Crazy Coco'), ('Sweetie Strawberry', 'Sweetie Strawberry'), ('Birthday Bonanza', 'Birthday Bonanza'), ('Loco Lemon', 'Loco Lemon'), ('White Coco Razz', 'White Coco Razz'), ('Gluten Free Cookie Craze', 'Gluten Free Cookie Craze'), ('Ridiculous Red Velvet', 'Ridiculous Red Velvet'), ('Scintillating Cinnamon', 'Scintillating Cinnamon'), ('Crisp Carrot', 'Crisp Carrot')], default='Very Vanilla', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='decoration',
            field=models.CharField(choices=[('Happy Birthday', 'Happy Birthday'), ('Graduation', 'Graduation'), ('Independence Day', 'Independence Day'), ('Thank You', 'Thank You'), ('Just Because', 'Just Because'), ('None', 'None')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='flavor',
            field=models.CharField(choices=[('Very Vanilla', 'Very Vanilla'), ('Crazy Coco', 'Crazy Coco'), ('Sweetie Strawberry', 'Sweetie Strawberry'), ('Birthday Bonanza', 'Birthday Bonanza'), ('Loco Lemon', 'Loco Lemon'), ('White Coco Razz', 'White Coco Razz'), ('Gluten Free Cookie Craze', 'Gluten Free Cookie Craze'), ('Ridiculous Red Velvet', 'Ridiculous Red Velvet'), ('Scintillating Cinnamon', 'Scintillating Cinnamon'), ('Crisp Carrot', 'Crisp Carrot')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='frosting_level',
            field=models.CharField(choices=[('None', 'None'), ('Drizzle', 'Drizzle'), ('Normal', 'Normal'), ('Extra', 'Extra')], default='Normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('Dozen Cupcakes', 'Dozen Cupcakes'), ('Personal Size Cake', 'Personal Size Cake'), ('Triple Tower Personal Size Cakes', 'Triple Tower Personal Size Cakes'), ('12 box of Personal Size Cakes', '12 box of Personal Size Cakes'), ('8 Inch Cake', '8 Inch Cake'), ('10 Inch Cake', '10 Inch Cake'), ('Layered Cake(10in bottom 8in top)', 'Layered Cake(10in bottom 8in top)')], max_length=100),
        ),
    ]
