# Generated by Django 4.0.6 on 2022-07-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_app', '0003_alter_guest_favorite_flavor_alter_order_decoration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
