# Generated by Django 4.0.6 on 2022-07-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes_app', '0003_cart_user_alter_guest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='previous',
            field=models.BooleanField(default=False),
        ),
    ]
